### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Yzubi** [maheshkurmi/libgdx-mario#1]
What is the license for the code? Do you have any plans in releasing it with the MIT/GPL license?

**Comment by maheshkurmi** [comment]
You can use it as you want.. It is absolutely free(note that I do no own
resources they are Nintendo property).
There is no license restriction on code
, but you can give credit (although not compulsory) .

I wrote it just for fun and testing capabilities of libgdx.

By the way you can also get super Mario in pure Android at my github.com
repo.(Search super Mario android in github.com to get it).
Once again there is no license restriction for code.

Happy coding

Regards
Mahesh Kurmi
SimPHY.com
